# Site
repository: pogist/pogist.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Murilo da Paixão
title: Senior Mobile & Web Developer
email: murilo.paixao.2@gmail.com

# Dark Mode (true/false/never)
darkmode: false 

# Social links
github_username: pogist
stackoverflow_username: "9494107"
linkedin_username: pogist

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Mobile and front-end developer based in Brazil focused on new and scalable technologies, who loves sharing knowledge, thinks analytically, and cares about self-improvement. Enjoys talking and studying about functional/reactive programming and web/mobile app architecture patterns.<br />
    - **Mobile:** 5+ years as a native mobile developer, mainly iOS/React Native, with working experience ranging
      from Swift/Objective-C native iOS apps to RN's native modules (Android and iOS) and CI/CD automation with fastlane.
    - **Front-end:** 3+ years experience working on large react.js projects, from RN apps to web dashboards,
      using modern web dev tools like typescript, pnpm, esbuild, vitejs etc.
    - **Back-end:** 3+ years experience working on node.js/typescript back-end projects using tools like
      nest.js, graphql, elasticsearch, docker, github actions and AWS stack.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: react-native-bitmovin-player
        link: https://github.com/take0ffmedia/react-native-bitmovin-player
        link_text: take0ffmedia/react-native-bitmovin-player
        quote: >
          An open-source react-native wrapper for Bitmovin's native player SDK.
        description: | # this will include new lines to allow paragraphs
          Added support for **picture-in-picture** mode detection on Android and wrote a [post](https://stackoverflow.com/questions/70110987/pass-onpictureinpicturemodechanged-result-into-a-react-native-module/70174114#70174114) on stackoverflow about it.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Beakyn
        sub_title: Senior Full-Stack Developer
        caption: fev. 2021 - Now
        link: https://beakyn.com/
        quote: >
          Beakyn supports many US companies, like <a href="https://www.outfrontmedia.com/">Outfront Media Inc.</a> - one of the biggest outdoor media companies in the world - with the datasets and tools needed to process and visualize US geodata.
        description: |
            - Design and develop features to the core API - a monolithic nest.js/graphql server written in typescript - which empowers all Beakyn's clients;
            - Add features and improvements to the Outfront's dashboard - the internal visualization tool used to interact with geographical data and media inventory - with tools like sass, react.js, redux, redux-sagas, etc.;
            - Develop a service in golang for fast data export in excel format.
      - layout: left
        title: Stone Co.
        sub_title: Mobile/React Native Developer
        caption: set. 2018 - fev. 2021
        link: https://www.stone.co/
        quote: >
          Stone Co. is a Brazilian fintech that provides many products and services to process physical and digital credit card payments.
        description: |
          During my time at Stone Co., I worked on a project called Ton - a product focused on helping individuals start and grow their businesses. And there I was responsible to:
            - Develop and improve an internal C library to parse and manipulate [ABECS](https://api.abecs.org.br/wp-content/uploads/2019/11/Certificac%CC%A7a%CC%83o-Abecs.pdf) protocol packets for communication between smartphones and low-energy bluetooth pinpads;
            - Develop and improve native mobile SDKs for both Android (Java) and iOS (Swift) to manage bluetooth communication and access to the ABECS parser C library;
            - Implement RN native modules for both Android (Java) and iOS (Objective-C) to bridge functionalities from the native SDKs;
            - Implement and improve features on the main app using typescript, react native, redux, redux-epics, rxjs, and other tools;
            - Automate app's continuous delivery process on circleCI with fastlane;
            - Implement and improve a few micro-services using node.js, AWS lambda, dynamodb, sqs, and other AWS stack services.
      - layout: left
        title: WiseGo
        sub_title: iOS App Developer
        caption: dez. 2017 - ago. 2018
        link: http://www.wisegoapp.com/
        quote: >
          A tourism startup focused on providing more autonomy and independence on the traveling experience.
        description: |
            - Implement and improve features of the native iOS app using Swift and GoogleMaps API.
      - layout: left
        title: Apple Developer Academy / IFCE
        sub_title: iOS Development Intern
        caption: jan. 2016 - dez. 2017
        link: http://developeracademy.ifce.edu.br/
        quote: >
          Educational program for iOS Developers aiming to grow them by training Swift/Objective-C and other Apple technologies.
        description: |
            - Develop educational apps using various Apple technologies eg. iOS, watchOs, tvOS, and macOS with Objective-C and Swift.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
